version: "3.8"

services:
  app:
    image: docker.io/arvaliullin/pyweb2024-image:v0.1
    ports:
      - "8082:8082"
    networks:
      - pyweb2024_network

  nginx:
    build:
      context: .
      dockerfile: deployments/Dockerfile.nginx
    ports:
      - "8081:8081"
    depends_on:
      - app
    networks:
      - pyweb2024_network

networks:
  pyweb2024_network:
    driver: bridge
